### ISSUE TITLE
지수가중이동평균(Exponentially Weighted Moving Average) 구현

### ISSUE THREAD

**Issue by yhur** [iot101-2023-Jeonjehyuk/OLED-Display#1]
수고했습니다.

그런데 지수가중이동평균(Exponentially Weighted Moving Average)이 구현이 안 되어 있네요.
구현해서 다시 push 하세요.

**Comment by jjh0313** [comment]
지수가중필터를 추가하여 영상과 코드를 다시 커밋했습니다. 피드백 감사합니다 교수님!
